# Generated by Django 4.2.1 on 2023-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('stationary', 'Stationary'), ('Vegetables', 'Vegetables'), ('Drinks', 'Drinks'), ('Fruits', 'Fruits'), ('Cereals', 'Cereals')], max_length=100),
        ),
    ]
